version: '3'

services:
  db:
    image: crowdcritic-db-img
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - 5432:5432
    volumes:
         - db_data:/var/lib/postgresql/data

volumes:
  db_data:

