-- INSERT INTO public.app_user ( email, name, phone_number, role, surname,password, username) VALUES
--                                                                                          ('kostas@mail.com', 'kostas', '2109876543', 0, 'agoris','$2a$12$ApFW90beaTwPYjwSn19KTuHGZudQES9RKdQUIl/nEjivq8Ezclspy
-- ' ,'kagoris'),
--                                                                                          ( 'stefanos@mail.com', 'stefanos', '2109876542', 1, 'vavoulas','12345678', 'svavoulas'),
--                                                                                          ( 'nikos@mail.com', 'nikos', '2109876541', 2, 'masouras','12345678', 'nmasouras'),
--                                                                                          ( 'dimitris@mail.com', 'dimitris', '2109876540', 0, 'mperos','12345678', 'dmperos'),
--                                                                                          ( 'ioannis@mail.com', 'ioannis', '2109876549', 1, 'sakarelos','12345678', 'isakarelos');
--
--
--
--
--
--
